### ISSUE TITLE
last.fm scrobbling feature

### ISSUE THREAD

**Issue by tjandt** [Rello/audioplayer#194] opened 2017-05-25 10:34 UTC
### Expected behavior

I would like to scrobble all my played tracks to last.fm or libre.fm
Is it possible to add this feature?

### Actual behavior

not avaiable yet ... new feature request

**Comment by xraMsamohT** [comment] 2017-05-25 10:50
Duplicate of #148

**Closed as completed by xraMsamohT** 2017-05-25 10:50 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:32
Duplicate of #148
