### ISSUE TITLE
Exclude Folders

### ISSUE THREAD

**Issue by 26op181** [Rello/audioplayer#71] opened 2016-10-20 12:25 UTC
The ability to exclude folders in the scan function.

**Comment by Rello** [comment] 2016-10-20 13:37
#39

**Comment by xraMsamohT** [comment] 2016-10-20 16:56
Duplicate of #66

**Closed as completed by xraMsamohT** 2016-10-20 16:56 UTC

**Comment by Rello** [comment] 2016-10-20 19:06
#39

**Comment by Rello** [comment] 2016-10-31 20:24
Feel free to add your opinion to the survery here:
https://help.nextcloud.com/t/help-on-include-exclude-filters-for-file-search/4694

**Comment by xraMsamohT** [comment] 2017-08-01 13:49
Duplicate of #66
