### ISSUE TITLE
Audio streaming .opus conversion

### ISSUE THREAD

**Issue by Maikewng** [Rello/audioplayer#281] opened 2018-02-17 12:37 UTC
Hello everyone! This is my first time on Github so please pardon me if I'm using the wrong tools or sections. I just recently started using the Audio Player app and I find it amazing! Still, as every new user, my eyes catch immediately small defects or lacking features which might not be evident to long time settled users.

I am an audiophile which stores his lossless music collection of .flac files on nextcloud, and I love to play them wherever I am through the Audio Player app. Still, .flac files are big (around 20MB each) and difficult to stream on networks with limited bandwith. They are also a problem when I'm on metered networks.
To circumvent these issues I keep a copy of them in .opus 128kbps format for streaming.

Wouldn't it be nice to have an option to convert my library in .opus format for efficient streaming? Using opusenc behind php should do the job quite efficiently. If the machine processor is quick enough it could be even done on the live stream.

I am curious of reading the thoughts of the community on the matter.

**Comment by xraMsamohT** [comment] 2018-02-17 15:47
Duplicate of #134

**Comment by Rello** [comment] 2018-03-03 11:48
Hello,
it is a nice case for a limited amount of users. and most users requested specifically flac support because of the high quality required.
From our side, we can not implement this feature because the resources are very limited and so is the use case.

To have something like this as an "app add-on" being provided by another developer would be a possible solution.

**Closed as completed by Rello** 2018-03-03 11:48 UTC
Labels: enhancement, won't fix
