### ISSUE TITLE
Unable to handle large-ish music folders

### ISSUE THREAD

**Issue by adolfintel** [Rello/audioplayer#209] opened 2017-06-19 10:07 UTC
### Expected behavior
It shows the list of tracks after scanning

### Actual behavior
It just keeps loading forever
![2017-06-19 11_49_38-audio player - owncloud - chromium](https://user-images.githubusercontent.com/16307689/27279693-b6b5ff5c-54e5-11e7-979d-0a4aeb990408.png)

### Steps to reproduce the behavior
1. Load a bunch of audio files in your music folder (in my case it was ~1200 files)
2. Scan
3. Open audio player

### Possible solution (optional)
I don't know how you're sending the list of songs, but maybe you should send the entire list at once as a big JSON file. Even with 1200 songs it shouldn't be more than ~100kb, Also, some caching may be useful I guess

### Server configuration
**Operating system**:
Debian 9.0 AMD64

**Web server:**
Apache 2.4.25

**Database:**
Sqlite

**PHP version:**
7

**Nextcloud/ownCloud version:** (see `/status.php`)
ownCloud 10.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Audio Player version:** (see `/settings/apps`)
2.0.2

**Where did you install Audio Player from:**
Owncloud's market

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Windows 10; Android 7.1.2

**Browser:**
Chromium 61 on both

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

It's huge, but I don't see any errors or warnings from AudioPlayer, just logged requests

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

No errors or warnings

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

No errors or warnings

</details>

**Comment by Rello** [comment] 2017-06-20 20:56
Hello @adolfintel 
thank you for reporting this.

can you have a look at the browser console/network information on the getcategoryitems file, which is being transferred?

This is in fact already a json file being transferred via oC/Nc standard.
Even so we reduced the amount of data drastically already, it will still be a lot more KBs here.
for every file we need to transfer all information you see in the list + backgrounds as mime-types, links and so on.

can you please validate if this ajax request was processed correctly?

**Comment by adolfintel** [comment] 2017-06-21 06:42
I just tried to make a test with 1500 copies of the same file. The getcategoryitems file was ~400kb and it loaded just fine, so I guess it's something in my music collection (some files have weird unicode names, could that be the problem?).
Right now I'm reuploading it (it will take a couple of hours), then I'll let you know.

**Comment by adolfintel** [comment] 2017-06-21 09:50
Yep, we get a nice 500 error
![2017-06-21 11_48_29-audio player - owncloud - chromium](https://user-images.githubusercontent.com/16307689/27378304-c0a0d878-5677-11e7-99d0-856304af002e.png)

**Comment by Rello** [comment] 2017-06-22 20:09
Hello,
i think your issue could be related to #214
where the metadata got much to big due to covers being sent.

could you try the commit by chance?

**Comment by adolfintel** [comment] 2017-06-22 20:14
I don't think it is related. In that issue, it gets a huge response, here I get a few kbytes with a server error page from owncloud. Besides, I had converted all the files with ffmpeg and stripped them of all metadata.
That said, if you want me to try something please tell me where to put the files

**Comment by Rello** [comment] 2017-06-22 20:19
can you please reproduce the error 500 on your side and right afterwards check the owncloud.log?
It should hopefully show the issue because it cant process the php for some reason

**Comment by adolfintel** [comment] 2017-06-22 20:22
Sure, I'll check it as soon as I come back home in a few hours

**Comment by adolfintel** [comment] 2017-06-23 05:43
I just checked the log, and it doesn't write anything when it fails.
I did find a few of these but I doubt they're related
```
{"reqId":"jqsfPeONKnVLhtedKnMS","level":3,"time":"2017-06-23T07:21:08+00:00","remoteAddr":"87.9.195.147","user":"dosse","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/apps\/audioplayer\/getcategoryitems?category=Folder&id=3372","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/html\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
```

**Comment by Rello** [comment] 2017-06-23 20:19
Hello,
i have now idea how to progress here. if your webserver gives a 500, it needs to have some issue.
anything in php-logs perhaps?
my only idea currently is that it is related to the data-overhead issue and the webserver/php ran into some kind of timeout or memory issue

**Comment by adolfintel** [comment] 2017-06-23 20:21
Honestly I don't know. i can see the files from owncloud's files app though.
Do you want access to the server? It's not like it's anything important anyways

**Comment by Rello** [comment] 2017-06-23 20:22
please contact me at 
audioplayer -at- scherello -dot- de

**Comment by adolfintel** [comment] 2017-06-23 20:23
I'll send you everything you need as soon as I get back home in a few hours.
Thank you 😊

**Comment by adolfintel** [comment] 2017-06-24 08:22
I think I just found the source of the problem. Apparently, there was a file that was not transcoded right, and was 0 bytes; I deleted it and it works.
The name of the file was ```benson, arizona.mkv.opus``` but audioplayer called it ```0benson, arizona.mkv.opus``` during the scan, if that's relevant.

**Closed as completed** 2017-06-24 08:23 UTC

**Comment by Rello** [comment] 2017-06-24 09:31
Can you still send the file to the mentioned email?
I would line to test
