### ISSUE TITLE
online radio

### ISSUE THREAD

**Issue by artemanufrij** [Rello/audioplayer#180] opened 2017-05-02 06:50 UTC
Hey @Rello, what do you think about a "playlist" for online radio?

**Comment by hitam4450** [comment] 2017-05-02 07:44
Well, this can be handled in the "regular" playlist issue!

https://github.com/Rello/audioplayer/issues/31

**Comment by xraMsamohT** [comment] 2017-05-02 09:12
Duplicate of #27 , See #39

**Closed as completed by xraMsamohT** 2017-05-02 09:12 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:38
Duplicate of #27
