### ISSUE TITLE
Limit Scan To Directory

### ISSUE THREAD

**Issue by thomaskonrad** [Rello/audioplayer#76] opened 2016-10-31 14:28 UTC
Hi,

I have my music collection inside a directory called "Music" in my ownCloud account. Now I would like Audio Player to scan for music only inside that directory. Is that possible?

Thanks
Thomas

**Comment by xraMsamohT** [comment] 2016-10-31 17:06
Duplicate of #66 
See #39

**Closed as completed by xraMsamohT** 2016-10-31 17:06 UTC

**Comment by Rello** [comment] 2016-10-31 20:24
Feel free to add your opinion to the survery here:
https://help.nextcloud.com/t/help-on-include-exclude-filters-for-file-search/4694

**Comment by xraMsamohT** [comment] 2017-08-01 13:49
Duplicate of #66
