### ISSUE TITLE
Seeking/Progressbar is broken when sidebar is open

### ISSUE THREAD

**Issue by kuluev** [Rello/audioplayer#231] opened 2017-09-18 13:13 UTC
### Steps to reproduce the behavior
1. Play something
2. Open sidebar
3. Try to seek

### Possible solution (optional)
Substract width of sidebar if sidebar is open

### Server configuration
**PHP version:**
last 7.*

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Migrated from last ownCloud

**Audio Player version:** (see `/settings/apps`)
2.1.0

**Where did you install Audio Player from:**
git

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
Local folder

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
win10 / debian

**Browser:**
Chrome 60.0.3112.113

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js?v=d9e6b5bb319a759d7ab1218c06d160f7-9:3650 Missing plural form in language file
_generatePluralFunction @ merged-template-prepend.js?v=d9e6b5bb319a759d7ab1218c06d160f7-9:3650
DevTools failed to parse SourceMap: https://myserver.com/nextcloud/core/vendor/dist/purify.min.js.map
```

</details>

**Comment by xraMsamohT** [comment] 2017-09-18 15:10
Duplicate of #111

**Closed as completed by xraMsamohT** 2017-09-18 15:10 UTC
