### ISSUE TITLE
Tracks do not auto-skip when screen is off or browser is in background

### ISSUE THREAD

**Issue by shockdude** [Rello/audioplayer#175] opened 2017-04-19 06:48 UTC
### Expected behavior
When a music track finishes, it should automatically skip to the next track, even if the web browser is in the background or the screen is off.

### Actual behavior
The track ends with silence. Turning the screen on or switching back to the browser automatically starts the next track.

### Steps to reproduce the behavior
1. Play song
2. Turn screen off/switch to a different app.
3. Let song play until the end
4. Silence
5. Turn screen on/switch back to the browser to auto-play the next track.

### Android Info
LG G4
Android 6.0
Using [Naked Browser](https://play.google.com/store/apps/details?id=com.fevdev.nakedbrowser), which is a barebones Android System WebView browser.

**Comment by xraMsamohT** [comment] 2017-04-19 08:16
Duplicate of #167 

See https://github.com/rello/audioplayer/issues/167#issuecomment-291240443

**Closed as completed by xraMsamohT** 2017-04-19 08:16 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:41
Duplicate of #167
