### ISSUE TITLE
poor performance on large number of files

### ISSUE THREAD

**Issue by berho** [Rello/audioplayer#237] opened 2017-09-28 10:57 UTC
### Expected behavior
UI react with quick response

### Actual behavior
UI does not show up or show up after a very long time

### Steps to reproduce the behavior
1. add hundreds of music files to NextCloud
2. access audio player

### Possible solution (optional)
* dynamicaly load portions of data
* paging
* check/create indices on database tables ?

### Server configuration

The NextCloud instance is running hosted on a shared server. 

**Operating system**:
Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux 

**Web server:** 
Apache

**Database:** 
mysqlnd 5.0.12-dev

**PHP version:**
php 7.0 

**Nextcloud/ownCloud version:** (see `/status.php`)
11.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Audio Player version:** (see `/settings/apps`)
2.1.0

**Where did you install Audio Player from:**
Apps

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local

**Are you using encryption:** yes/no
yes

### Client configuration
**Operating system:**
Windows 7

**Browser:**
latest Firefox

### NextCloud Logs:
**sometimes** log entries from audioplayer:

```
Error	PHP	Undefined index: mpeg at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/module.audio.mp3.php#1631	2017-09-27T17:41:01+0200
Error	PHP	Undefined index: mpeg at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/module.audio.mp3.php#1630	2017-09-27T17:41:01+0200
Error	PHP	Undefined index: mpeg at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/module.audio.mp3.php#1629	2017-09-27T17:41:01+0200
Error	PHP	fread() expects parameter 1 to be resource, null given at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/getid3.php#1705	2017-09-27T17:41:01+0200
Error	PHP	ftell() expects parameter 1 to be resource, null given at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/getid3.php#1682	2017-09-27T17:41:01+0200
Error	PHP	fseek() expects parameter 1 to be resource, null given at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/getid3.php#1740	2017-09-27T17:41:01+0200
Error	PHP	Undefined index: mpeg at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/module.audio.mp3.php#1631	2017-09-27T17:41:01+0200
Error	PHP	Undefined index: mpeg at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/module.audio.mp3.php#1630	2017-09-27T17:41:01+0200
Error	PHP	Undefined index: mpeg at /htdocs/cloud/apps/audioplayer/3rdparty/getid3/module.audio.mp3.php#1629	2017-09-27T17:41:01+0200

```

Hello,

thank you for audioplayer! It is very useful for me as I can hear my own music everywhere I am!

As my music library grows very large (~6000 titles) it has become painfull using it: I have to wait very long time (minutes) bevore the UI displays albums or when selecting "Albums", "Genres" etc...

Sometimes no answer is comming back from server at all but about every 30 seconds the client sends a GET request with URL

`https://myserverurl/ocs/v2.php/apps/notifications/api/v2/notifications`

in the background and get back

```
ocs | Object
meta | Object
status | ok
statuscode | 200
message | OK
data | []
```

**Comment by Rello** [comment] 2017-09-29 13:14
Hello,
we need to figure out where the issue is and we need your support using the browser debugger/inspectore.

* open the network tab of the inspector of the browser
* select one of the categories e.g. "Genres" in the dropdown.
* A file called getcategories?category=Genre is being loaded
* please post the size and the time of the transfer
* klick one of the Genres
* A file called getcategoryitems?category=Genre&categoryId=* is being loaded
* please post the size and the time of the transfer

in general, 6000 files should not be an issue especially when using the category display.

**Comment by berho** [comment] 2017-10-03 12:02
Sorry for the delay!

I updated to NC 12.0.3 but the performance of AudioPlayer is not better there...

The output from network inspector:

```
Request:
GET /index.php/apps/audioplayer/getmusic
Answer:
Warning: SyntaxError: JSON.parse: unterminated string at line 1 column 1063988 of the JSON data
Data: {"status":"success","data":{"albums":[{"id":"3355","nam":....
Time:
Warten: → 167457 ms
Empfangen: → 1170 ms

Request:
GET /index.php/apps/audioplayer/getcategory?category=Genre
Answer:
Data: JSON |  
status | success
data | [125]
0 | Object
:
Time:
Warten:→ 2215 ms
Empfangen:→ 0 ms

Request:
GET /index.php/apps/audioplayer/getcategoryitems?category=Genre&categoryId=598
Answer:
Data: JSON |  
status | success
data | [323]
0 | Object
:
Time:
Warten:→ 5475 ms
Empfangen:→ 63 ms
```

As you can see is the main problem the call to "getmusic" taking  **167457 ms**

Regards

**Comment by Rello** [comment] 2017-10-03 18:24
Hello,
Getmusic is that big, because it is transferring everything for the Albums grafical Display. Thiy will never be a really usefull display format for 6000 titles I would say.

But once you selected a category, it should remember this for the next start and you dont need to go via the Albums.

But still, the load of 5seconds for 323 titles within your Genre is quite high!
As its purely Database read, are you sure you are on mysql not sqlite? Is your shared hoster performing better in other operations as you would expect?

With the next release we will finetune the DB indices a little, but thats not that much of a potential compared to your 5sec.
Can you please check how big that file is?

**Comment by berho** [comment] 2017-10-09 08:57
Answer from Getmusic:
content-type: application/json; charset=utf-8
content-length: 1518424

When select another app in NC and switch back to audio player the selected album does not restore...

**Comment by Rello** [comment] 2017-11-03 20:06
Hello,
do you have any update here? the runtimes on your database seem very hich.
Is NC performing fast enough in the other areas like calendar & contacts?

**Comment by berho** [comment] 2017-11-06 10:48
Hello,

the performance of the shared server is ok but contacts take a while to begin display too but only several seconds (280 entries)...

At the moment I select an entry from the dropdown to get the albums or artist I want to hear and this is fast enough. The problem is that the spinner is staying on screen...

**Comment by MG2R** [comment] 2017-11-20 12:01
I'm running NC 12 on a dedicated box and have just shy of 4000 files in my library. Most usage is fine, but bringing up the list of all songs takes quite a few seconds. Once the list is loaded, everything is as snappy as ever. Firefox debug tools show me that most time is spent waiting for the server response.

![image](https://user-images.githubusercontent.com/5439592/33017361-6462ff4e-cdf2-11e7-8633-725a68840ab9.png)

How long is it "expected" to take for a collection this large? Other Nextcloud performance is snappy after the initial load..

**Comment by Rello** [comment] 2017-11-20 16:25
Hello,
thank you for contacting us.
Actually, your response times are pretty impressive! you are talking about the All-Titles selection which is generating ALL your 4000 files inkl. descriptions, artists & link information.
3 seconds for this actually very fast.

we might have some performance optimization in the future - but for the moment thats as good as it can get

**Comment by Rello** [comment] 2017-12-16 20:37
Hello,
please let us know if you encounter any other issues. as mentioned, a 3 second display is acceptable for this huge amount of titles and I would not know what to enhance there

**Closed as completed by Rello** 2017-12-16 20:37 UTC
Labels: playlist

**Comment by MG2R** [comment] 2017-12-17 22:48
> what to enhance there

Have no idea how feasible this is, but wouldn't it be possible to generate and send out the metadata in chunks? This way the initial response is much faster, and the browser doesn't hang as long trying to download/parse a giant metadata list.

**Comment by Rello** [comment] 2019-08-22 21:21
@berho 
do you have an NC setup where you could test the current AP beta version?
we made a HUGE step forward. Cover-View for all and **BIG** UI  + scanner speedup

would like to hear some feedback from you guys with the big libraries if possible...

**Comment by berho** [comment] 2019-09-04 08:37
Yes, this is a HUGE step forward ;)
At the moment I have about 5000 files in the library and the speed is fine. It take about 5 seconds to get responsible again when navigating to "all titles" and about half a second to see the titles when I click on an album.

Only sometimes I get "connection to server lost" message in the UI and I noticed that there are always 18 new files found when scanning for new files but 0 are added as they are recognized as duplicates.

Thanks for the great job!

**Comment by Rello** [comment] 2019-09-05 20:27
@berho 
thank you for your feedback.

yes. there is no "flagging" in place to mark the duplicates for not being scanned again
