### ISSUE TITLE
Direct Play in Files App

### ISSUE THREAD

**Issue by nc2017** [Rello/audioplayer#161] opened 2017-03-22 13:02 UTC
It would be nice to be able to play and forward/backward (best including a scroll bar) audio files directly from the folders where they reside, without having to enter audio player app. This is helpful for users who work on different projects which include many types of documents, but only limited audio files.

**Comment by xraMsamohT** [comment] 2017-03-22 16:09
Duplicate of #131 #147

**Closed as completed by xraMsamohT** 2017-03-22 16:09 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:45
Duplicate of #131 #147
