### ISSUE TITLE
Show Progress and Control Buttons in Files app

### ISSUE THREAD

**Issue by Huster-at-github** [Rello/audioplayer#147] opened 2017-02-21 07:53 UTC
I have tons of internet radio recordings, some up to 5 hours per "track".

When browsing through that stuff with Files App (Audio Player is too slow) it would be great not only to play a track.

So I friendly ask for this enhancement:

Open **Progress and Control Buttons View** on top when playing from **Files App**.

**Comment by xraMsamohT** [comment] 2017-02-21 08:03
Duplicate of #131

**Closed as completed by xraMsamohT** 2017-02-21 08:03 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:46
Duplicate of #131
