### ISSUE TITLE
Multi select songs to add/remove to/from playlist

### ISSUE THREAD

**Issue by kees-closed** [Rello/audioplayer#302] opened 2018-04-29 19:42 UTC
It would be nice to be able to select multiple songs and add/remove them from a playlist. Now it's a one-by-one operation, which isn't very rewarding.

**Comment by xraMsamohT** [comment] 2018-04-29 19:47
Duplicate of #168

**Comment by Rello** [comment] 2018-12-09 19:56
Hello,
due to the limited time available + the limited use case, unfortunately I can not proceed with this request

**Closed as completed by Rello** 2018-12-09 19:56 UTC
Labels: enhancement, playlist
