### ISSUE TITLE
Add ID3_TAG COLUMN: Stars

### ISSUE THREAD

**Issue by garzy** [Rello/audioplayer#261] opened 2017-12-18 12:20 UTC
Hi, I love your audioplayer for nextcloud and I would like to see the column "stars" in the table because I work with this id3v2 field in the MediaMonkey app (http://www.mediamonkey.com/)  for classify my mp3 files. 

I'm developer and I could collaborate in whatever I can (because I'm java developer not javascript developer but I can defend :)

http://id3.org/id3v2.3.0  (@see 4.18. Popularimeter)

http://help.mp3tag.de/main_tags.html#MM  (@see MediaMonkey Rating)

https://en.wikipedia.org/wiki/ID3  (@see ID3v2 rating tag issue)

http://forum.mediamonkey.com/viewtopic.php?f=4&t=64204

Thanks In Advance!

**Comment by xraMsamohT** [comment] 2017-12-18 13:25
Duplicate of #103

**Closed as completed by xraMsamohT** 2017-12-18 13:25 UTC
