### ISSUE TITLE
pls. make audioplayer compatible to NC12.0.0

### ISSUE THREAD

**Issue by Wikinaut** [Rello/audioplayer#192] opened 2017-05-22 20:54 UTC
After upgrade to NC 12.0.0, the App is disabled and not loaded in NC 12.0.0.

**Comment by Rello** [comment] 2017-05-22 20:56
duplicate of #190

we are just in final testing and will release the new version very soon

**Closed as completed** 2017-05-22 23:00 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:37
Duplicate of #190
