### ISSUE TITLE
Support for cover images in separate files

### ISSUE THREAD

**Issue by kernel1024** [Rello/audioplayer#85] opened 2016-11-14 23:11 UTC
I noticed, that audioplayer extracts cover images only from id3 tags. Internets also have many old albums with cover images placed in separate picture files, without picture field in tags.

So, i decided to write small patch for such feature:
https://github.com/kernel1024/audioplayer/commit/93ddd119fc1aeb55b21439ab38c86fa31548ffe0

**Comment by xraMsamohT** [comment] 2016-11-14 23:43
Duplicate of #24 
See #39

**Comment by Rello** [comment] 2016-11-15 07:04
Hello @kernel1024 
thank you for your suggestion. unfortunately this approach only works on internal files. not on external and encrypted. because then the "filename" is only a php tempfile. so there is no folder

But we will have a look at it. It will be a good basis and I will try to combine it with the tempfile-logic.

I will keep you updated

**Comment by Rello** [comment] 2016-12-01 21:51
Implementation was started...

**Comment by Rello** [comment] 2016-12-03 11:45
#97

**Comment by kernel1024** [comment] 2016-12-03 14:31
Cool.

Clementine player also have configurable list of cover images:
![001](https://cloud.githubusercontent.com/assets/11448390/20859949/60a9fb40-b986-11e6-8486-d9aa4d36ed13.png)

**Comment by Rello** [comment] 2016-12-03 15:15
@kernel1024 
sorry, wrong reference.
this is the main issue where it i being processed (currently in testing already)
#24

**Closed as completed** 2016-12-15 22:24 UTC

**Comment by xraMsamohT** [comment] 2017-08-01 13:47
Duplicate of #24
