### ISSUE TITLE
special characters in folder names (one click play)

### ISSUE THREAD

**Issue by dennmuel** [Rello/audioplayer#291] opened 2018-04-10 08:39 UTC
### Expected behavior
Click on a mp3 file in any folder and it starts to play.

### Actual behavior
Mp3 files within the music folder are played, but files in another directory (e.g. Documents) are not.

### Steps to reproduce the behavior
1. Click on file outside the music directory.
2. 
3. 

### Additional information (optional)
Music directory is shared, others are not.

### Server configuration
**Operating system**:
Raspbian, Linux 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

**Web server:**
Apache 2.4.25

**Database:**
mysql

**PHP version:**
7.0.27

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated, no version gap

**Audio Player version:** (see `/settings/apps`)
2.2.5

**Where did you install Audio Player from:**
Nextcloud app store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No.

**Are you using encryption:** yes/no
No.

### Client configuration
**Operating system:**
Win7

**Browser:**
Firefox 59.0.2 (64-Bit)

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
{"reqId":"ekF6i5sjXQ9LJymC3o49","level":3,"time":"2018-04-10T08:20:34+00:00","remoteAddr":"134.155.36.91","user":"dennis","app":"PHP","method":"GET","url":"\/index.php\/apps\/audioplayer\/getaudiostream?file=Bands%20&%20Kunst\/Mojosoundz\/Vorbereitung\/7__Mojosoundz%20-%20Probe%202017_06-20%20-%2009%20-%20Ready%20or%20not.mp3","message":"fopen(\/var\/www\/nextcloud\/data\/dennis\/files\/Bands ): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#282","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
HTTP-Content-Type "text/html" wird nicht unterstützt. Laden der Medienressource https://kuchenplatte.spdns.de/index.php/apps/audioplayer/getaudiostream?file=Bands%20&%20Kunst/Mojosoundz/Vorbereitung/7__Mojosoundz%20-%20Probe%202017_06-20%20-%2009%20-%20Ready%20or%20not.mp3 fehlgeschlagen.

Medien konnte nicht abgespielt werden. Keine Dekoder für angefragte Formate: text/html

```
(Rough english translation: text/html not supported. Loading of resource http://etc... failed. Could not play media. No decoder for formats: text/html)
</details>

**Comment by Rello** [comment] 2018-04-15 19:30
Hello,
thank you for your input and sorry for the late feedback. we are just busy with the next release of AP.

I am not sure about your issue.
some questions:
1. does the issue also occur for other files?
2. does this issue also occor, if you move/copy the file to your user root folder?
3. are there any other files which do play? (no general issue)
4. did you index the Audio Player app (scann library) and try to play this title from there?

please let me know,

thank you

**Comment by dennmuel** [comment] 2018-05-02 07:31
Hello and sorry for the late reply (been on a vacation),

I updated to NC 13.0.2 and AP 2.3.0 and checked again. Regarding your questions:

> does the issue also occur for other files?

Yes, it does.

> does this issue also occor, if you move/copy the file to your user root folder?

No. When moved to the user root folder the file is being played directly from the folder.

> are there any other files which do play? (no general issue)

Yes in the sense that files in the (indexed) music folder play.
No in the sense that all the other files in the separate (not indexed) folder (e.g. `userroot/Documents/my_awesome_band/rehearsal`) do not play either.

> did you index the Audio Player app (scann library) and try to play this title from there?

When I reset the library of the AP app, configure it to scan in `userroot/Documents/my_awesome_band/rehearsal` and rescan it, then the files play from the app but still do not play when they are clicked on in the folder.

Please let me know, if I can provide further information.

Many thanks and best regards
Dennis

**Comment by RotterMartin** [comment] 2018-08-09 11:52
It seems that the issue is caused by certain chars in the file- or pathname (e.g. "+" or "&"). In my case I could make the mp3 files play in the files-app by renaming the parent folder from "video + audio" to "video and audio".  So it looks like the audioplayer app does not handle filenames and paths correctly.

**Comment by Rello** [comment] 2018-08-12 06:39
thank you for the valuable hint!
I will look into this - having an idea already

**Comment by Rello** [comment] 2018-09-23 17:50
issue is solved. sorry for the late reply. v.2.4 will be released soon

**Closed as completed** 2018-09-23 19:19 UTC
Labels: bug

**Comment by dennmuel** [comment] 2018-09-24 06:17
No worries, thanks for your effort! :)

**Comment by RotterMartin** [comment] 2018-09-24 10:03
Thanks a lot!
